apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-vite-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-vite-app
  template:
    metadata:
      labels:
        app: my-vite-app
    spec:
      containers:
        - name: my-vite-app
          image: vamsiacr.azurecr.io/vite-app:latest  # Use the same tag as in the GitHub Actions workflow
          imagePullPolicy: Always  # Ensure Kubernetes always pulls the latest image
