name: Deploy Vite.js App to AKS

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (Vite.js needs Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite.js app
      - name: Build Vite.js app
        run: npm run build

      # Step 5: Log in to Azure using Service Principal credentials
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Log in to ACR
      - name: Log in to ACR
        run: |
          az acr login --name vamsiacr

      # Step 7: Build Docker image and tag it
      - name: Build Docker image
        run: |
          docker build -t vamsiacr.azurecr.io/vite-app:latest .

      # Step 8: Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push vamsiacr.azurecr.io/vite-app:latest

      # Step 9: Deploy to AKS
      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group vamsi --name vamsiaks
          kubectl apply -f aks/deployment.yml
          kubectl apply -f aks/service.yml
          kubectl get pods
          kubectl get services
